discord:
  token: YOUR_BOT_DISCORD_TOKEN
  authorized_users:
    - "123456789012345678" # Replace with actual Discord user IDs
    - "234567890123456789"
  # DO NOT TOUCH THE FOLLOWING VALUES MANUALLY:
  # They are managed by the plugin and will be overwritten.
  server_id: ""
  channel_id: ""
  webhook_url: ""