main: com.tylerflar.MineCordLink
name: MineCord-Link
version: ${project.version}
api-version: 1.13
description: Link your minecraft server to discord
authors: [TylerFlar]
website: https://github.com/TylerFlar/MineCord-Link
commands:
  minecordlink:
    description: Reload the MineCord-Link configuration
    usage: /<command> reload
  coords:
    description: Share your current coordinates
    usage: /<command> [location name]
  linkdiscord:
    description: Generate or enter a code to link your Minecraft account to Discord
    usage: /<command> [code]
  togglelistener:
    description: Toggle individual listeners on or off
    usage: /<command> <listener> <on|off>
    permission: minecordlink.togglelistener
permissions:
  minecordlink.reload:
    description: Allows reloading the MineCord-Link configuration
    default: op
  minecordlink.togglelistener:
    description: Allows toggling individual listeners
    default: op